on: [push]
name: test
jobs:
  test:
    name: Run test on GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['latest']
        cabal: ['latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          git config --global user.email "john@example.com"
          git config --global user.name "John Doe"
          cabal test --test-show-details=direct
  lint:
    name: Check format on GHC ${{ matrix.ghc }}
    steps:
      - uses: haskell-actions/run-ormolu@v14
  build:
    name: Build on GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['latest']
        cabal: ['latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build
